In [13]:
#tento kod vypise prumer, smerodatnou odchylku, max and min, jednou pomoci knihovny numpy podruhe pomoci standartniho pythonu 
import numpy as np 
from time import *
import random
import math


a = np.random.randint(1, 101, size=10)
print(a)

mean = np.mean(a)
std_dev = np.std(a)
max_value = np.max(a)
min_value = np.min(a)

print(f"Průměr: {mean}")
print(f"Směrodatná odchylka: {std_dev}")
print(f"Max: {max_value}")
print(f"Min: {min_value}\n")


a1 = [random.randint(1, 100) for _ in range(10)]
print(a1)

mean = sum(a1) / len(a1)

squared_diffs = [(x - mean) ** 2 for x in a1]
variance = sum(squared_diffs) / len(a1)
std_dev = math.sqrt(variance)

max_value = max(a1)
min_value = min(a1)

print(f"Průměr: {mean}")
print(f"Směrodatná odchylka: {std_dev}")
print(f"Max: {max_value}")
print(f"Min: {min_value}\n")

[75 66  9 62 10 61 36 91 60 51]
Průměr: 52.1
Směrodatná odchylka: 25.220824728783157
Max: 91
Min: 9

[90, 37, 90, 21, 10, 74, 45, 13, 42, 64]
Průměr: 48.6
Směrodatná odchylka: 28.320310732758564
Max: 90
Min: 10



In [14]:
#tento kod vypise vysledek maticoveho nasobeni a  čas potřebný pro každé řešení, jednou pomoci numpy podruhe podle standartniho pythonu
start_time = time()

a1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a2 = np.array([[9,8,7], [6,5,4], [3,2,1]])
a3 = np.dot(a1, a2)
print(f"Maticove nasobeni vysledek: \n {a3}")

stop_time = time()
print(f"uplynuly cas: {stop_time-start_time}")

start_time1 = time()

a4 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a5 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
a6 = list(zip(*a5))
a7 = []

for row in a4:
    temp_row = []  
    for col in a6:   
        temp_row.append(sum(map(lambda x, y: x * y, row, col)))
    a7.append(temp_row)  
   
print(f"Maticove nasobeni vyskedek: \n {a7}")
        


stop_time1 = time()
print(f"uplynuly cas: {stop_time1-start_time1}")


Maticove nasobeni vysledek: 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
uplynuly cas: 0.0
Maticove nasobeni vyskedek: 
 [[30, 24, 18], [84, 69, 54], [138, 114, 90]]
uplynuly cas: 0.0


In [15]:
#tento kod vypise vysledek skalarniho soucin a  čas potřebný pro každé řešení, jednou pomoci numpy, podruhe pomoci standartniho pythonu
start_time = time()

a1 = np.arange(1000)
a2 = np.arange(1000)
a3 = np.dot(a1, a2)
print(f"skalarni soucin: {a3}")


stop_time = time()
print(f"uplynuly cas: {stop_time-start_time}")

start_time1 = time()

a4 = list(range(1000))
a5 = list(range(1000))
a6 = list(zip(a4,a5))
a7 = 0
for value, value1 in a6:
    a7 += value * value1


print(f"skalarni soucin: {a7}")
stop_time1 = time()
print(f"uplynuly cas: {stop_time1-start_time1}")

skalarni soucin: 332833500
uplynuly cas: 0.0012938976287841797
skalarni soucin: 332833500
uplynuly cas: 0.0


In [16]:
#Tento kód řeší soustavu lineárních rovnic a měří čas potřebný pro každé řešení jednou pomoci numpy podruhe pomoci standartniho pythonu
start_time = time()
a = np.array([[1,5], [3,2]])
b = np.array([11,7])

x = np.linalg.solve(a, b)
print("solution with numpy")
print(x)
stop_time = time()
print(f"uplynuly cas: {stop_time-start_time}")

start_time1 = time()

def gaussian_elimination(a, b):
    n = len(b)
    
    
    for i in range(n):
        if a[i][i] == 0:
            raise ValueError("Matrix is singular and cannot be solved.")
        
        for j in range(i + 1, n):
            ratio = a[j][i] / a[i][i]
            for k in range(i, n):
                a[j][k] -= ratio * a[i][k]
            b[j] -= ratio * b[i]
    
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = b[i]
        for j in range(i + 1, n):
            x[i] -= a[i][j] * x[j]
        x[i] /= a[i][i]
    
    return x

a = [[1, 5], [3, 2]]
b = [11, 7]


solution = gaussian_elimination(a, b)

print("standard python solution:")
print(solution)
stop_time1 = time()
print(f"uplynuly cas: {stop_time1-start_time1}")

solution with numpy
[1. 2.]
uplynuly cas: 0.007015705108642578
standard python solution:
[1.0, 2.0]
uplynuly cas: 0.0


In [17]:
#tento kod vypise vysledek faktorialu, jednou pomoci numpy podruhe pomoci standartniho pythonu
from scipy.special import factorial

start_time = time()

n = 30
a1 = factorial(n, exact=True)
print(f"vysledek faktorialu n: {a1}")

stop_time = time()
print(f"uplynuly cas: {stop_time-start_time}")

start_time1 = time()

a2 = 1   
for i in range(2, n + 1):
    a2 *= i  
print(f"vysledek faktorialu n: {a2}")
stop_time1 = time()
print(f"uplynuly cas: {stop_time1-start_time1}")




vysledek faktorialu n: 265252859812191058636308480000000
uplynuly cas: 0.0016589164733886719
vysledek faktorialu n: 265252859812191058636308480000000
uplynuly cas: 0.0
